@startuml



Prototype <|-- PrototypeA



class Prototype <<abstract>>
{
    + {abstract} clone() : std::unique_ptr<Prototype>
}

class PrototypeA
{
    + PrototypeA(const PrototypeA& clone)
    + clone() : std::unique_ptr<Prototype>
}



@enduml
