@startuml Singleton

SomeInterface <|.. SomeSingleton



interface SomeInterface
{
    + void doSomething()
}

class SomeSingleton
{
    - SomeSingleton theInstance
    
    - construct()
    |||
    + void doSomething() override
    |||
    + SomeSingleton getInstance
}
